name: Compiling
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: sudo apt install ffmpeg
      - uses: actions/setup-python@v5
      - run: pip install scons
      - run: scons -j4 target=template_debug platform=linux arch=x86_64 use_system=yes
